<a href="https://colab.research.google.com/github/jeeva477/DL_Skill_Tracker/blob/main/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# ============================================================
# Input image and kernel
# ============================================================

image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=float)

kernel = np.array([
    [1, 0],
    [0, 1]
], dtype=float)

# ============================================================
# im2col function
# ============================================================

def im2col(image, kernel_size=2, stride=1, padding=0):

    # Apply padding
    image = np.pad(
        image,
        ((padding, padding), (padding, padding)),
        mode="constant"
    )

    H, W = image.shape
    k = kernel_size

    out_h = (H - k) // stride + 1
    out_w = (W - k) // stride + 1

    cols = []

    for i in range(0, H - k + 1, stride):
        for j in range(0, W - k + 1, stride):
            patch = image[i:i+k, j:j+k].reshape(-1)
            cols.append(patch)

    return np.array(cols), out_h, out_w

# ============================================================
# Convolution using matrix multiplication
# ============================================================

cols, out_h, out_w = im2col(
    image,
    kernel_size=2,
    stride=1,
    padding=0
)

kernel_vector = kernel.reshape(-1)

output = cols @ kernel_vector

output = output.reshape(out_h, out_w)

# ============================================================
# Display results
# ============================================================

print("im2col matrix:")
print(cols)

print("\nKernel vector:")
print(kernel_vector)

print("\nConvolution output:")
print(output)

im2col matrix:
[[1. 2. 4. 5.]
 [2. 3. 5. 6.]
 [4. 5. 7. 8.]
 [5. 6. 8. 9.]]

Kernel vector:
[1. 0. 0. 1.]

Convolution output:
[[ 6.  8.]
 [12. 14.]]
